<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ssp_model extends CI_Model
{

    public $table = 'ssp';
    public $id = 'ssp_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {$this->db->join('nama_wp', 'nama_wp.nama_wp_id = ssp.nama_wp_id', 'left');
        $this->db->join('akun_pajak', 'akun_pajak.akun_pajak_id = ssp.akun_pajak_id', 'left');
        $this->db->join('kode_jenis_setoran', 'kode_jenis_setoran.kode_jenis_setoran_id = ssp.kode_jenis_setoran_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('nama_wp', 'nama_wp.nama_wp_id = ssp.nama_wp_id', 'left');
        $this->db->join('akun_pajak', 'akun_pajak.akun_pajak_id = ssp.akun_pajak_id', 'left');
        $this->db->join('kode_jenis_setoran', 'kode_jenis_setoran.kode_jenis_setoran_id = ssp.kode_jenis_setoran_id', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ssp_id', $q);
	$this->db->or_like('kkp_wajib_pajak', $q);
	$this->db->or_like('nama_wp_id', $q);
	$this->db->or_like('nop', $q);
	$this->db->or_like('alamat_nop', $q);
	$this->db->or_like('tahun_pajak', $q);
	$this->db->or_like('masa_pajak', $q);
	$this->db->or_like('akun_pajak_id', $q);
	$this->db->or_like('kode_jenis_setoran_id', $q);
	$this->db->or_like('uraian_pembayaran', $q);
	$this->db->or_like('no_ketetapan', $q);
	$this->db->or_like('jumlah_pembayan', $q);
	$this->db->or_like('lokasi_pelaporan', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nama_wp_penyetor', $q);
	$this->db->or_like('npwp_wp_penyetor', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('created', $q);
	$this->db->or_like('user_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('nama_wp', 'nama_wp.nama_wp_id = ssp.nama_wp_id', 'left');
        $this->db->join('akun_pajak', 'akun_pajak.akun_pajak_id = ssp.akun_pajak_id', 'left');
        $this->db->join('kode_jenis_setoran', 'kode_jenis_setoran.kode_jenis_setoran_id = ssp.kode_jenis_setoran_id', 'left');

        $this->db->order_by($this->id, $this->order);
        $this->db->group_start();
        $this->db->like('ssp_id', $q);
	$this->db->or_like('kkp_wajib_pajak', $q);
	$this->db->or_like('nama_wp', $q);
	$this->db->or_like('nop', $q);
	$this->db->or_like('alamat_nop', $q);
	$this->db->or_like('tahun_pajak', $q);
	$this->db->or_like('masa_pajak', $q);
	$this->db->or_like('kode_akun_pajak', $q);
	$this->db->or_like('kode_jenis_setoran', $q);
	$this->db->or_like('uraian_pembayaran', $q);
	$this->db->or_like('no_ketetapan', $q);
	$this->db->or_like('jumlah_pembayan', $q);
	$this->db->or_like('lokasi_pelaporan', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nama_wp_penyetor', $q);
	$this->db->or_like('npwp_wp_penyetor', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('created', $q);
	$this->db->or_like('user_id', $q);
    $this->db->group_end();
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ssp_model.php */
/* Location: ./application/models/Ssp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-06 09:22:34 */
/* http://harviacode.com */